# Generated by Django 4.1.7 on 2023-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_item_details_item_img_url_item_name_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=50, unique=True)),
                ('email', models.CharField(default='email', max_length=100, unique=True)),
                ('password', models.CharField(default='password', max_length=200)),
            ],
        ),
    ]
