# Generated by Django 4.1.7 on 2023-03-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0004_rename_user_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
